"""
Django settings for ecommerce_nexus project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import environ
from pathlib import Path
from datetime import timedelta
import dj_database_url



# Initialize environment variables
env = environ.Env(DEBUG=(bool, False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure we explicitly read .env located in BASE_DIR (same folder as manage.py)
env_path = BASE_DIR / ".env"
if env_path.exists():
    environ.Env.read_env(str(env_path))
# If .env is absent, env('...') calls will raise and let you know what is missing.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])  # change "*" in prod


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "drf_yasg",
    "catalog",
    "django.contrib.postgres",
    "accounts",  
    "rest_framework_simplejwt.token_blacklist",  # <- required for logout/blacklist
    "idempotency_key",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ecommerce_nexus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ecommerce_nexus.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ---------- Development-friendly DB / Cache / Celery config ----------
# Use environment toggles so you can switch to Postgres/Redis for production.
# Default: quick local dev using SQLite + in-memory cache + eager Celery.

USE_POSTGRES = env.bool("USE_POSTGRES", default=False)

# --- 1. If using DATABASE_URL from Railway/Render, ALWAYS use it ---
DATABASE_URL = env("DATABASE_URL", default=None)

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
        )
    }

# --- 2. If no DATABASE_URL but USE_POSTGRES=True ---
elif USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("POSTGRES_DB", default="ecommerce_db"),
            "USER": env("POSTGRES_USER", default="ecommerce_user"),
            "PASSWORD": env("POSTGRES_PASSWORD", default="strongpassword"),
            "HOST": env("POSTGRES_HOST", default="127.0.0.1"),
            "PORT": env("POSTGRES_PORT", default="5432"),
        }
    }

# --- 3. Final fallback: SQLite ---
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# REST Framework Configuration
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
    
    'DEFAULT_RENDERER_CLASSES': [
    'rest_framework.renderers.JSONRenderer',
],

}

SIMPLE_JWT = {
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# Caching Configuration
# https://docs.djangoproject.com/en/4.2/topics/cache/

# Cache config: use Redis only if explicitly enabled
USE_REDIS = env.bool("USE_REDIS", default=False)
if USE_REDIS and USE_POSTGRES:
    REDIS_HOST = env("REDIS_HOST", default="127.0.0.1")
    REDIS_PORT = env.int("REDIS_PORT", default=6379)
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
else:
    # Simple in-memory cache for local dev
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-dev-cache",
        }
    }
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# --- Static files (for production) ---
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Optional: compressed manifest storage (recommended)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery (development mode: tasks run synchronously so no broker required)
# In production or when USE_POSTGRES & USE_REDIS are true you can change these envs.
CELERY_ALWAYS_EAGER = env.bool("CELERY_ALWAYS_EAGER", default=True)
CELERY_TASK_ALWAYS_EAGER = CELERY_ALWAYS_EAGER  # Celery older/newer keys
CELERY_TASK_EAGER_PROPAGATES = env.bool("CELERY_TASK_EAGER_PROPAGATES", default=True)

if not CELERY_ALWAYS_EAGER and USE_REDIS:
    # broker url only used when not running eager mode
    CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=f"redis://{env('REDIS_HOST','127.0.0.1')}:{env.int('REDIS_PORT',6379)}/0")
else:
    CELERY_BROKER_URL = "memory://"
# Optional: results backend when not eager
if not CELERY_ALWAYS_EAGER and USE_REDIS:
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL
else:
    CELERY_RESULT_BACKEND = "django-db"  # safe default; requires django-celery-results if you want DB results
# -------------------------------------------------------------------

# Email
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@example.com"
