# Generated by Django 4.2.26 on 2025-11-24 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_populate_product_public_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
