# Generated by Django 4.2.26 on 2025-11-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
