# Generated by Django 4.2.26 on 2025-11-27 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_inventorymovement_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("actor", models.CharField(blank=True, max_length=255, null=True)),
                ("action", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("object_pk", models.CharField(blank=True, max_length=255, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.user",
                    ),
                ),
            ],
        ),
    ]
